application:
  title: Bookshelf
  version: 0.0.1

bookshelf:
  some-number: 11
  some-text: More information

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:./testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookshelf

custom:
  # Don't do this in an actual production application! Passwords should never be stored in files checked into version control.
  # Use environment variables or a secrets management system instead.
  admin:
    password: $2a$10$7v/Mv2BAz5mg9tlBXFV3/ePEgEDRbp/BdavFTmOE78IrEiaDwMDfC # = 'password'
